# Generated by Django 5.0 on 2024-04-22 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_email_userprofile_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('HOD_CSE', 'HOD_CSE'), ('HOD_MECH', 'HOD_MECH'), ('HOD_CIVIL', 'HOD_CIVIL'), ('HOD_EEE', 'HOD_EEE'), ('HOD_ECE', 'HOD_ECE'), ('Principal', 'Principal'), ('Event_Manager', 'Event_Manager'), ('Assistant Professor', 'Assistant Professor')], max_length=200),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('approval', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorie')),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.venue')),
            ],
        ),
    ]
