# Generated by Django 5.0 on 2024-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
