# Generated by Django 5.0 on 2024-04-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_enddate_event_endtime_event_startdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chief_guest',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
